# Generated by Django 3.2.8 on 2021-11-22 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chats',
            name='group_name',
            field=models.CharField(default='1', max_length=20),
            preserve_default=False,
        ),
    ]
