# Generated by Django 3.2.8 on 2021-11-22 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_auto_20211122_0845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chats',
            name='invite_accepted',
        ),
    ]
